name: churn-prediction-env

channels:
  - conda-forge
  - defaults
  
dependencies:
  - python=3.10
  - pip
  - pandas=2.0.3
  - numpy=1.24.3
  - pyarrow=12.0.1
  - scikit-learn=1.3.0
  - imbalanced-learn=0.11.0
  - joblib=1.3.2
  - pyyaml=6.0.1
  - matplotlib=3.7.2
  - seaborn=0.12.2
  - pip:
      - azureml-inference-server-http  # Servidor de inferência
      - azureml-ai-monitoring          # Monitoramento
      - werkzeug==2.2.3                
      - flask==2.2.5                   
      - marshmallow==3.19.0
      - mlflow==2.9.2
      - mlflow-skinny==2.9.2
      - azureml-mlflow==1.57.0
      - azure-ai-ml==1.11.1
      - azure-identity==1.14.0
      - xgboost==2.0.3
      - lightgbm==4.3.0